#!/bin/bash

function find_extended_classes() {
  grep -R --include '*.js' --include '*.coffee' \
    '^[ 	]*[a-zA-Z_\.0-9]\+ = *[a-zA-Z0-9_\.]\+\.extend' . | \
    sed -E "s/^([^:]*):[ 	]*((.*\.)*)([^=\. ]*)( *= *)([^\( ]*).*$/\4	\1	\/\3\4\5\6\//"

  # 1 - filename
  # 2 - namespace
  # 3 - namespace
  # 4 - class name
  # 5 - space ( = )
  # 6 - base class
}

function find_coffee_classes() {
  grep -R --include '*.coffee' \
    '^[ 	]*class[ 	]\+[a-zA-Z_\.0-9]\+' . | \
    sed -E "s/^([^:]*):[ 	]*(class[ 	]+)((.*\.)*)([^=\. ]*)(.*)$/\5	\1	\/\2\4\5\6\//"

  # 1 - filename
  # 2 - class
  # 3 - namespace
  # 4 - namespace
  # 5 - className
  # 6 - definition
}

function find_js_methods() {
  grep -R --include '*.js' \
    '^[ 	]*[a-zA-Z_\.0-9]\+ *[=:] function' . | \
    sed -E "s/^([^:]*):[ 	]*(.*\.)?([^=:\. ]+)( *[:=] *)(.*)$/\3	\1	\/\2\3\4\5\//"

  # 1 - filename
  # 2 - namespace
  # 3 - name
  # 4 - space
  # 5 - definition
}

function find_coffee_methods() {
  grep -R --include '*.coffee' -E \
    '^[ 	]*[a-zA-Z_\.0-9]+ *[=:] *(\([^\)]+\))? *[=-]>' . | \
    sed -E "s/^([^:]*):[ 	]*(.*\.)?([^=:\. ]+)( *[:=] *)(.*)$/\3	\1	\/\2\3\4\5\//"

  # 1 - filename
  # 2 - namespace
  # 3 - name
  # 4 - space
  # 5 - definition
}

function find_static_coffee_objects() {
  grep -R --include '*.coffee' -E \
    '^[A-Z][a-zA-Z_\.0-9]* *= *$' . | \
    sed -E "s/^([^:]*):[ 	]*(.*\.)?([^=:\. ]+)( *=) *$/\3	\1	\/\2\3\4\//"
  
  # 1 - filename
  # 2 - namespace
  # 3 - name
  # 4 - space
  # 5 - definition
}

function find_static_js_objects() {
  grep -R --include '*.js' -E \
    '^[A-Z][a-zA-Z_\.0-9]* *= *{ *$' . | \
    sed -E "s/^([^:]*):[ 	]*(.*\.)?([^=:\. ]+)( *= *{) *$/\3	\1	\/\2\3\4\//"
  
  # 1 - filename
  # 2 - namespace
  # 3 - name
  # 4 - space
  # 5 - definition
}

(
find_extended_classes
find_static_coffee_objects
find_static_js_objects
find_js_methods
find_coffee_classes
find_coffee_methods
) | sort
