#!/bin/bash

function find_extended_classes() {
  grep -R --include '*.js' --include '*.coffee' \
    '^[ \t]*[a-zA-Z_\.0-9]\+ = *[a-zA-Z0-9_\.]\+\.extend' . | \
    sed -E "s/^([^:]*):[ 	]*((.*\.)*)([^=\. ]*)( *= *)([^\( ]*).*$/\4	\1	\/\3\4\5\6\//" | \
    sort

  # 1 - filename
  # 2 - namespace
  # 3 - namespace
  # 4 - class name
  # 5 - space ( = )
  # 6 - base class
}

find_extended_classes
