#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P $DIR && pwd)

function run_test() {
  type=$1
  echo "Testing $type"
  (
    cd $DIR
    ../bin/${type}tagger > /tmp/tagger.output
    if [ "`diff -q expected-$type-tags /tmp/tagger.output`" != "" ]; then
      vimdiff -R expected-$type-tags /tmp/tagger.output
    fi
  )
}

function run_ctags_test() {
  type=$1
  echo "Testing $type"
  (
    cd $DIR
    ctags -f - input.$type > /tmp/tagger.output
    if [ "`diff -q expected-$type-ctags /tmp/tagger.output`" != "" ]; then
      vimdiff -R expected-$type-ctags /tmp/tagger.output
    fi
  )
}


run_ctags_test js
run_ctags_test coffee

run_test css
run_test ruby

