#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P $DIR && pwd)

function run_test() {
  type=$1
  echo "Testing $type"
  (
    cd $DIR
    ../${type}tagger > /tmp/tagger.output
    if [ "`diff -q expected-$type-tags /tmp/tagger.output`" != "" ]; then
      vimdiff -R expected-$type-tags /tmp/tagger.output
    fi
  )
}


run_test js
run_test css
run_test ruby
